DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS unit CASCADE;
DROP TABLE IF EXISTS device CASCADE;
DROP TABLE IF EXISTS squad CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS person_to_unit CASCADE;
DROP TABLE IF EXISTS device_to_unit CASCADE;
DROP TABLE IF EXISTS unit_to_squad CASCADE;