DROP TABLE IF EXISTS users CASCADE ;
DROP TABLE IF EXISTS personal CASCADE ;
DROP TABLE IF EXISTS unit CASCADE ;
DROP TABLE IF EXISTS device_type CASCADE ;
DROP TABLE IF EXISTS device CASCADE ;
DROP TABLE IF EXISTS user_to_unit CASCADE ;
DROP TABLE IF EXISTS conversation CASCADE ;
DROP TABLE IF EXISTS message CASCADE ;
DROP TABLE IF EXISTS user_conversation CASCADE ;
DROP TABLE IF EXISTS device_location CASCADE ;
DROP TABLE IF EXISTS task CASCADE ;
DROP TABLE IF EXISTS user_to_task CASCADE ;
DROP TABLE IF EXISTS current_user_task CASCADE;
DROP INDEX IF EXISTS idx_users_rule_level;
DROP INDEX IF EXISTS idx_personal_name_surname;
DROP INDEX IF EXISTS idx_device_type;
DROP INDEX IF EXISTS idx_message_user_id;
DROP INDEX IF EXISTS idx_message_sent_at;
DROP INDEX IF EXISTS idx_message_user_conversation;
DROP INDEX IF EXISTS idx_device_location_device_id ;
DROP INDEX IF EXISTS idx_device_location_changed_at;
DROP INDEX IF EXISTS idx_device_location_device_time ;
DROP INDEX IF EXISTS idx_device_location_geography;
DROP INDEX IF EXISTS idx_task_state;
DROP INDEX IF EXISTS idx_task_completion_date;
DROP INDEX IF EXISTS idx_user_to_task_user_id;
DROP INDEX IF EXISTS idx_current_user_task_user_id;
DROP INDEX IF EXISTS idx_task_state_user;