DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS unit CASCADE;
DROP TABLE IF EXISTS device CASCADE;
DROP TABLE IF EXISTS squad CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS user_to_unit CASCADE;
DROP TABLE IF EXISTS device_to_unit CASCADE;
DROP TABLE IF EXISTS unit_to_squad CASCADE;