DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS unit CASCADE;
DROP TABLE IF EXISTS device CASCADE;
DROP TABLE IF EXISTS user_to_unit CASCADE;
DROP TABLE IF EXISTS personal CASCADE;
DROP TABLE IF EXISTS conversation CASCADE;
DROP TABLE IF EXISTS user_conversation CASCADE;
DROP TABLE IF EXISTS message CASCADE;
DROP TABLE IF EXISTS device_type CASCADE ;
DROP TABLE IF EXISTS device_location CASCADE ;

DROP INDEX IF EXISTS idx_users_email ;
DROP INDEX IF EXISTS idx_unit_name;
DROP INDEX IF EXISTS idx_device_name ;
DROP INDEX IF EXISTS idx_device_owner;
DROP INDEX IF EXISTS idx_user_to_unit_unit ;
DROP INDEX IF EXISTS idx_message_conversation_sent;
DROP INDEX IF EXISTS idx_user_conversation_user;
DROP INDEX IF EXISTS idx_user_conversation_conv;
DROP INDEX IF EXISTS idx_user_conversation_last_seen;