name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: filename
    attributes:
      label: File name (optional)
      description: If the bug is related to a specific file, please provide the file name.
      placeholder: "ex. index.js, style.css, README.md"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please attach any screenshots that help illustrate the issue. You can drag and drop images here.
      placeholder: Drag and drop screenshots here or paste image URLs
    validations:
      required: false