name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Describe your feature idea in detail.
      placeholder: "I would like to see..."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature?
      options:
        - Nice to have
        - Would be useful
        - Really needed
        - Critical
      default: 0
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or mockups
      description: Optional screenshots, mockups, or examples to illustrate your idea.
      placeholder: "Drag and drop images here..."
    validations:
      required: false