// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: types.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RuleLevel     uint64                 `protobuf:"varint,2,opt,name=ruleLevel,proto3" json:"ruleLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetRuleLevel() uint64 {
	if x != nil {
		return x.RuleLevel
	}
	return 0
}

type Personal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Personal) Reset() {
	*x = Personal{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Personal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Personal) ProtoMessage() {}

func (x *Personal) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Personal.ProtoReflect.Descriptor instead.
func (*Personal) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *Personal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Personal) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	RuleLvl       int32                  `protobuf:"varint,4,opt,name=rule_lvl,json=ruleLvl,proto3" json:"rule_lvl,omitempty"`
	Personal      *Personal              `protobuf:"bytes,5,opt,name=personal,proto3" json:"personal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRuleLvl() int32 {
	if x != nil {
		return x.RuleLvl
	}
	return 0
}

func (x *User) GetPersonal() *Personal {
	if x != nil {
		return x.Personal
	}
	return nil
}

type Unit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsConfigured  bool                   `protobuf:"varint,3,opt,name=isConfigured,proto3" json:"isConfigured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unit) Reset() {
	*x = Unit{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *Unit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Unit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Unit) GetIsConfigured() bool {
	if x != nil {
		return x.IsConfigured
	}
	return false
}

type PID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PID) Reset() {
	*x = PID{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *PID) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IsServerRunning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsServerRunning) Reset() {
	*x = IsServerRunning{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsServerRunning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsServerRunning) ProtoMessage() {}

func (x *IsServerRunning) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsServerRunning.ProtoReflect.Descriptor instead.
func (*IsServerRunning) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

type Running struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Running) Reset() {
	*x = Running{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Running) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Running) ProtoMessage() {}

func (x *Running) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Running.ProtoReflect.Descriptor instead.
func (*Running) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

type StartApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartApp) Reset() {
	*x = StartApp{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartApp) ProtoMessage() {}

func (x *StartApp) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartApp.ProtoReflect.Descriptor instead.
func (*StartApp) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

type PingServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingServer) Reset() {
	*x = PingServer{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingServer) ProtoMessage() {}

func (x *PingServer) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingServer.ProtoReflect.Descriptor instead.
func (*PingServer) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

type LoginUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           *PID                   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUser) Reset() {
	*x = LoginUser{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUser) ProtoMessage() {}

func (x *LoginUser) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUser.ProtoReflect.Descriptor instead.
func (*LoginUser) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

func (x *LoginUser) GetPid() *PID {
	if x != nil {
		return x.Pid
	}
	return nil
}

func (x *LoginUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AcceptLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	RuleLevel     int64                  `protobuf:"varint,2,opt,name=rule_level,json=ruleLevel,proto3" json:"rule_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptLogin) Reset() {
	*x = AcceptLogin{}
	mi := &file_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptLogin) ProtoMessage() {}

func (x *AcceptLogin) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptLogin.ProtoReflect.Descriptor instead.
func (*AcceptLogin) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptLogin) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *AcceptLogin) GetRuleLevel() int64 {
	if x != nil {
		return x.RuleLevel
	}
	return 0
}

type DenyLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyLogin) Reset() {
	*x = DenyLogin{}
	mi := &file_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyLogin) ProtoMessage() {}

func (x *DenyLogin) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyLogin.ProtoReflect.Descriptor instead.
func (*DenyLogin) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{14}
}

func (x *DenyLogin) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type GetLoggedInUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           *PID                   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoggedInUUID) Reset() {
	*x = GetLoggedInUUID{}
	mi := &file_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoggedInUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoggedInUUID) ProtoMessage() {}

func (x *GetLoggedInUUID) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoggedInUUID.ProtoReflect.Descriptor instead.
func (*GetLoggedInUUID) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{15}
}

func (x *GetLoggedInUUID) GetPid() *PID {
	if x != nil {
		return x.Pid
	}
	return nil
}

type LoggedInUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggedInUUID) Reset() {
	*x = LoggedInUUID{}
	mi := &file_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggedInUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggedInUUID) ProtoMessage() {}

func (x *LoggedInUUID) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggedInUUID.ProtoReflect.Descriptor instead.
func (*LoggedInUUID) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{16}
}

func (x *LoggedInUUID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NeededServerConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerPID     *PID                   `protobuf:"bytes,1,opt,name=serverPID,proto3" json:"serverPID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeededServerConfiguration) Reset() {
	*x = NeededServerConfiguration{}
	mi := &file_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeededServerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeededServerConfiguration) ProtoMessage() {}

func (x *NeededServerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeededServerConfiguration.ProtoReflect.Descriptor instead.
func (*NeededServerConfiguration) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{17}
}

func (x *NeededServerConfiguration) GetServerPID() *PID {
	if x != nil {
		return x.ServerPID
	}
	return nil
}

type CreateUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsConfigured  bool                   `protobuf:"varint,2,opt,name=isConfigured,proto3" json:"isConfigured,omitempty"`
	UserID        string                 `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUnit) Reset() {
	*x = CreateUnit{}
	mi := &file_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnit) ProtoMessage() {}

func (x *CreateUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnit.ProtoReflect.Descriptor instead.
func (*CreateUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{18}
}

func (x *CreateUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUnit) GetIsConfigured() bool {
	if x != nil {
		return x.IsConfigured
	}
	return false
}

func (x *CreateUnit) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type AcceptCreateUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCreateUnit) Reset() {
	*x = AcceptCreateUnit{}
	mi := &file_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCreateUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCreateUnit) ProtoMessage() {}

func (x *AcceptCreateUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCreateUnit.ProtoReflect.Descriptor instead.
func (*AcceptCreateUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{19}
}

type DenyCreateUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyCreateUnit) Reset() {
	*x = DenyCreateUnit{}
	mi := &file_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyCreateUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyCreateUnit) ProtoMessage() {}

func (x *DenyCreateUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyCreateUnit.ProtoReflect.Descriptor instead.
func (*DenyCreateUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{20}
}

func (x *DenyCreateUnit) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type GetAllUnits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUnits) Reset() {
	*x = GetAllUnits{}
	mi := &file_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUnits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUnits) ProtoMessage() {}

func (x *GetAllUnits) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUnits.ProtoReflect.Descriptor instead.
func (*GetAllUnits) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{21}
}

type AllUnits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*Unit                `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllUnits) Reset() {
	*x = AllUnits{}
	mi := &file_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllUnits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUnits) ProtoMessage() {}

func (x *AllUnits) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUnits.ProtoReflect.Descriptor instead.
func (*AllUnits) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{22}
}

func (x *AllUnits) GetUnits() []*Unit {
	if x != nil {
		return x.Units
	}
	return nil
}

type LoginUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUnit) Reset() {
	*x = LoginUnit{}
	mi := &file_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUnit) ProtoMessage() {}

func (x *LoginUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUnit.ProtoReflect.Descriptor instead.
func (*LoginUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{23}
}

func (x *LoginUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ========================
// USER OPERATIONS
// ========================
type CreateUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUser) Reset() {
	*x = CreateUser{}
	mi := &file_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUser) ProtoMessage() {}

func (x *CreateUser) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUser.ProtoReflect.Descriptor instead.
func (*CreateUser) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{24}
}

func (x *CreateUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AcceptCreateUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCreateUser) Reset() {
	*x = AcceptCreateUser{}
	mi := &file_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCreateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCreateUser) ProtoMessage() {}

func (x *AcceptCreateUser) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCreateUser.ProtoReflect.Descriptor instead.
func (*AcceptCreateUser) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{25}
}

type DenyCreateUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyCreateUser) Reset() {
	*x = DenyCreateUser{}
	mi := &file_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyCreateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyCreateUser) ProtoMessage() {}

func (x *DenyCreateUser) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyCreateUser.ProtoReflect.Descriptor instead.
func (*DenyCreateUser) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{26}
}

func (x *DenyCreateUser) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type GetAllUsersInUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` //unit uuid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersInUnit) Reset() {
	*x = GetAllUsersInUnit{}
	mi := &file_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersInUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersInUnit) ProtoMessage() {}

func (x *GetAllUsersInUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersInUnit.ProtoReflect.Descriptor instead.
func (*GetAllUsersInUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{27}
}

func (x *GetAllUsersInUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AllUsersInUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllUsersInUnit) Reset() {
	*x = AllUsersInUnit{}
	mi := &file_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllUsersInUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUsersInUnit) ProtoMessage() {}

func (x *AllUsersInUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUsersInUnit.ProtoReflect.Descriptor instead.
func (*AllUsersInUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{28}
}

func (x *AllUsersInUnit) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserAboveLVL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lvl           int32                  `protobuf:"varint,1,opt,name=lvl,proto3" json:"lvl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAboveLVL) Reset() {
	*x = GetUserAboveLVL{}
	mi := &file_types_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAboveLVL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAboveLVL) ProtoMessage() {}

func (x *GetUserAboveLVL) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAboveLVL.ProtoReflect.Descriptor instead.
func (*GetUserAboveLVL) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{29}
}

func (x *GetUserAboveLVL) GetLvl() int32 {
	if x != nil {
		return x.Lvl
	}
	return 0
}

type UsersAboveLVL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersAboveLVL) Reset() {
	*x = UsersAboveLVL{}
	mi := &file_types_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersAboveLVL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersAboveLVL) ProtoMessage() {}

func (x *UsersAboveLVL) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersAboveLVL.ProtoReflect.Descriptor instead.
func (*UsersAboveLVL) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{30}
}

func (x *UsersAboveLVL) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type IsUserInUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserInUnit) Reset() {
	*x = IsUserInUnit{}
	mi := &file_types_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserInUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserInUnit) ProtoMessage() {}

func (x *IsUserInUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserInUnit.ProtoReflect.Descriptor instead.
func (*IsUserInUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{31}
}

func (x *IsUserInUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserInUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInUnit) Reset() {
	*x = UserInUnit{}
	mi := &file_types_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInUnit) ProtoMessage() {}

func (x *UserInUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInUnit.ProtoReflect.Descriptor instead.
func (*UserInUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{32}
}

type UserNotInUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotInUnit) Reset() {
	*x = UserNotInUnit{}
	mi := &file_types_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotInUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotInUnit) ProtoMessage() {}

func (x *UserNotInUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotInUnit.ProtoReflect.Descriptor instead.
func (*UserNotInUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{33}
}

type AssignUserToUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserToUnit) Reset() {
	*x = AssignUserToUnit{}
	mi := &file_types_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserToUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserToUnit) ProtoMessage() {}

func (x *AssignUserToUnit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserToUnit.ProtoReflect.Descriptor instead.
func (*AssignUserToUnit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{34}
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05types\"8\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\truleLevel\x18\x02 \x01(\x04R\truleLevel\"8\n" +
	"\bPersonal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\"\x90\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x19\n" +
	"\brule_lvl\x18\x04 \x01(\x05R\aruleLvl\x12+\n" +
	"\bpersonal\x18\x05 \x01(\v2\x0f.types.PersonalR\bpersonal\"N\n" +
	"\x04Unit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fisConfigured\x18\x03 \x01(\bR\fisConfigured\"/\n" +
	"\x03PID\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x11\n" +
	"\x0fIsServerRunning\"\t\n" +
	"\aRunning\"\n" +
	"\n" +
	"\bStartApp\"\f\n" +
	"\n" +
	"PingServer\"\f\n" +
	"\n" +
	"Disconnect\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"[\n" +
	"\tLoginUser\x12\x1c\n" +
	"\x03pid\x18\x01 \x01(\v2\n" +
	".types.PIDR\x03pid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"@\n" +
	"\vAcceptLogin\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\x12\x1d\n" +
	"\n" +
	"rule_level\x18\x02 \x01(\x03R\truleLevel\"\x1f\n" +
	"\tDenyLogin\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\"/\n" +
	"\x0fGetLoggedInUUID\x12\x1c\n" +
	"\x03pid\x18\x01 \x01(\v2\n" +
	".types.PIDR\x03pid\"\x1e\n" +
	"\fLoggedInUUID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x19NeededServerConfiguration\x12(\n" +
	"\tserverPID\x18\x01 \x01(\v2\n" +
	".types.PIDR\tserverPID\"\\\n" +
	"\n" +
	"CreateUnit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fisConfigured\x18\x02 \x01(\bR\fisConfigured\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\"\x12\n" +
	"\x10AcceptCreateUnit\"$\n" +
	"\x0eDenyCreateUnit\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\"\r\n" +
	"\vGetAllUnits\"-\n" +
	"\bAllUnits\x12!\n" +
	"\x05units\x18\x01 \x03(\v2\v.types.UnitR\x05units\"\x1b\n" +
	"\tLoginUnit\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"-\n" +
	"\n" +
	"CreateUser\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.types.UserR\x04user\"\x12\n" +
	"\x10AcceptCreateUser\"$\n" +
	"\x0eDenyCreateUser\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\"#\n" +
	"\x11GetAllUsersInUnit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x0eAllUsersInUnit\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.types.UserR\x05users\"#\n" +
	"\x0fGetUserAboveLVL\x12\x10\n" +
	"\x03lvl\x18\x01 \x01(\x05R\x03lvl\"2\n" +
	"\rUsersAboveLVL\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.types.UserR\x05users\"\x1e\n" +
	"\fIsUserInUnit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\f\n" +
	"\n" +
	"UserInUnit\"\x0f\n" +
	"\rUserNotInUnit\"\x12\n" +
	"\x10AssignUserToUnitB&Z$github.com/janicaleksander/bcs/Protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_types_proto_goTypes = []any{
	(*Role)(nil),                      // 0: types.Role
	(*Personal)(nil),                  // 1: types.Personal
	(*User)(nil),                      // 2: types.User
	(*Unit)(nil),                      // 3: types.Unit
	(*PID)(nil),                       // 4: types.PID
	(*IsServerRunning)(nil),           // 5: types.IsServerRunning
	(*Running)(nil),                   // 6: types.Running
	(*StartApp)(nil),                  // 7: types.StartApp
	(*PingServer)(nil),                // 8: types.PingServer
	(*Disconnect)(nil),                // 9: types.Disconnect
	(*Ping)(nil),                      // 10: types.Ping
	(*Pong)(nil),                      // 11: types.Pong
	(*LoginUser)(nil),                 // 12: types.LoginUser
	(*AcceptLogin)(nil),               // 13: types.AcceptLogin
	(*DenyLogin)(nil),                 // 14: types.DenyLogin
	(*GetLoggedInUUID)(nil),           // 15: types.GetLoggedInUUID
	(*LoggedInUUID)(nil),              // 16: types.LoggedInUUID
	(*NeededServerConfiguration)(nil), // 17: types.NeededServerConfiguration
	(*CreateUnit)(nil),                // 18: types.CreateUnit
	(*AcceptCreateUnit)(nil),          // 19: types.AcceptCreateUnit
	(*DenyCreateUnit)(nil),            // 20: types.DenyCreateUnit
	(*GetAllUnits)(nil),               // 21: types.GetAllUnits
	(*AllUnits)(nil),                  // 22: types.AllUnits
	(*LoginUnit)(nil),                 // 23: types.LoginUnit
	(*CreateUser)(nil),                // 24: types.CreateUser
	(*AcceptCreateUser)(nil),          // 25: types.AcceptCreateUser
	(*DenyCreateUser)(nil),            // 26: types.DenyCreateUser
	(*GetAllUsersInUnit)(nil),         // 27: types.GetAllUsersInUnit
	(*AllUsersInUnit)(nil),            // 28: types.AllUsersInUnit
	(*GetUserAboveLVL)(nil),           // 29: types.GetUserAboveLVL
	(*UsersAboveLVL)(nil),             // 30: types.UsersAboveLVL
	(*IsUserInUnit)(nil),              // 31: types.IsUserInUnit
	(*UserInUnit)(nil),                // 32: types.UserInUnit
	(*UserNotInUnit)(nil),             // 33: types.UserNotInUnit
	(*AssignUserToUnit)(nil),          // 34: types.AssignUserToUnit
}
var file_types_proto_depIdxs = []int32{
	1, // 0: types.User.personal:type_name -> types.Personal
	4, // 1: types.LoginUser.pid:type_name -> types.PID
	4, // 2: types.GetLoggedInUUID.pid:type_name -> types.PID
	4, // 3: types.NeededServerConfiguration.serverPID:type_name -> types.PID
	3, // 4: types.AllUnits.units:type_name -> types.Unit
	2, // 5: types.CreateUser.user:type_name -> types.User
	2, // 6: types.AllUsersInUnit.users:type_name -> types.User
	2, // 7: types.UsersAboveLVL.users:type_name -> types.User
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
